name: FontProof
on: [push, pull_request]
jobs:
  fontproof:
    runs-on: ubuntu-latest
    name: FontProof
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: FontProof
        id: fontproof
        uses: docker://siletypesetter/fontproof:latest
        with:
          args: proofs.sil
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: proofs
          path: proofs.pdf
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
